### ISSUE TITLE
Reordering pawns by dragging portraits

### ISSUE THREAD

**Issue by Aviuz** [Aviuz/PrisonLabor#111]
Description *	
Not a bug per se, but for some reason the "Prison Labor" mod makes it so reordering pawns by right-click-dragging their portraits (the ones between your resource count and the Learning Helper) no longer reorders them on the "Assign" tab.

**Comment by Hazzer** [comment]
Should not be a problem since [v1.3.0](https://github.com/Aviuz/PrisonLabor/releases/tag/1.3.0)
