### ISSUE TITLE
Jailor attempt to recruit prisoners

### ISSUE THREAD

**Issue by Aviuz** [Aviuz/PrisonLabor#121]
> Must be a bug. I doubled checked his chat log and he is indeed asking prisoners (very recently) to join, even though he's marked to only do jailor work. I stopped trying to have seprate jailors/wardens due to this being an issue weeks of gameplay ago.   Have no idea what would be causing it though.

**Comment by Hazzer** [comment]
Should work correctly since [v1.3.6](https://github.com/Aviuz/PrisonLabor/releases/tag/1.3.6)
