### ISSUE TITLE
Resocialization error resulting in non-useable pawn

### ISSUE THREAD

**Issue by GreatWhiteMuffloN** [Aviuz/PrisonLabor#125]
Accepting the re-socialization offer from the prisoner results in the following error; 

Exception in RimWorld.ThinkNode_ConditionalColonist TryIssueJobPackage: System.NullReferenceException: Object reference not set to an instance of an object
at (wrapper dynamic-method) RimWorld.JobGiver_Work.TryIssueJobPackage_Patch1 (object,Verse.Pawn,Verse.AI.JobIssueParams) <0x0051c>
at Verse.AI.ThinkNode_Priority.TryIssueJobPackage (Verse.Pawn,Verse.AI.JobIssueParams) <0x00130>

Verse.Log:Error(String, Boolean)
Verse.AI.ThinkNode_Priority:TryIssueJobPackage(Pawn, JobIssueParams)
Verse.AI.ThinkNode_Conditional:TryIssueJobPackage(Pawn, JobIssueParams)
Verse.AI.ThinkNode_Priority:TryIssueJobPackage(Pawn, JobIssueParams)
Verse.AI.Pawn_JobTracker:DetermineNextJob(ThinkTreeDef&)
Verse.AI.Pawn_JobTracker:TryFindAndStartJob()
Verse.AI.Pawn_JobTracker:JobTrackerTick()
Verse.Pawn:Tick_Patch1(Object)
Verse.TickList:Tick()
Verse.TickManager:DoSingleTick()
Verse.TickManager:TickManagerUpdate()
Verse.Game:UpdatePlay()
Verse.Root_Play:Update()

and the pawn is unusable;

![unuseable](https://user-images.githubusercontent.com/33177721/49377112-8c92d700-f709-11e8-9020-4740e234be80.PNG)

**Comment by Aviuz** [comment]
it seems like work settings didn't got initialized
