### ISSUE TITLE
Prisoners attempting to use the same workbench

### ISSUE THREAD

**Issue by Aviuz** [Aviuz/PrisonLabor#130]
1. Set up a workbench and set it to "Prisoners Only". Set crafting to the highest priority for two or more prisoners.
2. The prisoners will now swap out each others work constantly on that workbench, so neither will ever complete any work.
3. The prisoners should occupy a workbench, so that another prisoner cannot take it from them. In this image: https://i.imgur.com/loA95Ek.png you can see that there are two workbenches, and two prisoners. Both workbenches are set to prisoners only, both prisoners have crafting at the highest priority. They refuse to go to the other workbench, and instead cut stuck on the first workbench. I have loads of mods, but none that should impact this.

**Comment by Hazzer** [comment]
Fixed
