### ISSUE TITLE
Forbidden bug still exists?

### ISSUE THREAD

**Issue by Aviuz** [Aviuz/PrisonLabor#134]
>Hello! I suspect you're already aware of this, but I wanted to let you know that for some reason when my prisoners mine steel, (And a few other choice items, Salt and medical herbs being two i've found) it will automatically forbid the item after they're done.
>
Someone posted a comment about this back in November, and in response you linked to your FAQ involving systemnullreferenceexception errors. So I tried to figure out which mod was causing the problem. Unfortunately after some trial and error. The only active mods remaining were; Core, prison labor, and locks. (In that order, but I did try reversing locks and prison labor) the problem still exists. I just wanted to let you know!
>
If there's any information that you would like me to provide, just let me know. Besides the described problem I have had no other issues with your mod and I wanted to say thank you for the wonderful work you've done!

**Comment by Aviuz** [comment]
gash darn it, RimWorld source code changed

I need to rewrite all patches for forbidden bug

**Comment by Aviuz** [comment]
Need to delay this issue for later development. This problem is to complex to fix it roght now.

**Comment by Hazzer** [comment]
Should be fixed for now.
