### ISSUE TITLE
No Water No Life Compatibility

### ISSUE THREAD

**Issue by Aviuz** [Aviuz/PrisonLabor#153]
> Once you fixed compatibility for 0.9x and it was working great, same for the 0.10 beta. But for 0.10 release I think the new feature that wardens won't bring food to prisoners who could reach it by themselves broke something here.
> When I have wounded prisoners, my doctors will bring them food but not water, and when they can walk they will stand up and get something to eat but nothing to drink, even when they are dehydrating.
> I have to test this a bit more, but I wanted to let you know already that there might be an issue, because a lot of people are playing with No Water No Life.
> Latest version: https://steamcommunity.com/sharedfiles/filedetails/?id=1541840184

**Comment by Hazzer** [comment]
Compatibility dropped
