### ISSUE TITLE
Prisoner Labor Area not working in 1.1

### ISSUE THREAD

**Issue by SpencerBelleau** [Aviuz/PrisonLabor#167]
The area doesn't seem to forbid colonist work properly anymore. I'm assuming that it's some issue with the new version since I recall this working in the past. Easy to reproduce if you just put the area over a bench of some kind with bills a colonist can fulfill.
Also important to note, just in case, that I have motivation toggled off in my game. Not sure if it'll affect this somehow but you never know.

**Comment by SpencerBelleau** [comment]
I realized that I may have been using bills wrong, but colonists still do perform other non-bill work in zones where they shouldn't, such as cleaning and farming, as well as hauling.

**Comment by Hazzer** [comment]
Should be fixed in v1.1.4
