### ISSUE TITLE
Prisoners stand indefinitley and don't work.

### ISSUE THREAD

**Issue by pirate1337** [Aviuz/PrisonLabor#169]
I have my prisoner set to mine out an area for me but he just gets out of his bed and does nothing. I turned motivation mechanics off and that did nothing to fix it.

**Comment by KMjolnir** [comment]
My friend and I were speaking today, we're having the same issue. We did notice that occasionally they'll build a roof if they can reach a spot that is designated to be roofed but that's it.

**Comment by Aviuz** [comment]
Duplicate #128
