### ISSUE TITLE
Forbidden Items from cutting

### ISSUE THREAD

**Issue by kaseyawolf2** [Aviuz/PrisonLabor#17]
When ever a prisoner cuts down a tree it makes the wood forbidden

Mods: http://steamcommunity.com/sharedfiles/filedetails/?id=973762506
home: yes
Prisoner: Raider

**Comment by Aviuz** [comment]
Yes I forgot about wood-cutting. Making item forbidden by non-colonists has ugly implementation and scattered all over a code.

Thanks for report

**Comment by kaseyawolf2** [comment]
just thought of something, haven't tested it yet, i check it out but what about foraging plants.

**Comment by Aviuz** [comment]
foraging plants it's same as wood-cutting

**Comment by Aviuz** [comment]
Fixed in 0.4
