### ISSUE TITLE
Prison Labor / Harmony

### ISSUE THREAD

**Issue by Wolvgar** [Aviuz/PrisonLabor#170]
Log https://gist.github.com/f1dec773fcd6888839d4048dfd998dd5

Hey there my load order for test
Harmony
Core
Hugslib
Jectools
Prison Labor

Throwing me 2 Errors
PrisonLaborException: FindOperandAfter() didn't find any lines. Trace: at PrisonLabor.HarmonyPatches.HPatcher.FindOperandAfter (System.Reflection.Emit.OpCode[]

HarmonyLib.HarmonyException: Patching exception in method virtual System.Void RimWorld.Dialog_BillConfig::DoWindowContents(UnityEngine.Rect inRect) ---> System.Exception: Wrong null argument: ldloc.s NULL [Label58, Label59, Label60]

Maybe you have an idea whats going on and can fix if it is on your side. <3 Thanks

**Comment by Jackobe93** [comment]
Hi,
I have same 2 errors, but this one is between them:

PrisonLaborException: failed to proceed harmony patches: Wrong null argument: ldloc.s NULL [Label58, Label59, Label60]

Load order:
Harmony
Core
HugsLib
Mod Manager
AllowTool
Prison Labor

Log:
https://gist.github.com/5b38dc1bd54253880f8f2974f140454a

Maybe it will help.
