### ISSUE TITLE
Error "Harmony patch failed to find "AddScrollToPrisonerTab3" fragment" .error

### ISSUE THREAD

**Issue by JacksonRoyal** [Aviuz/PrisonLabor#174]
https://gist.github.com/HugsLibRecordKeeper/5a8a4e2aa5b4568cf83f631148cf8ce7 (Line 182-192 Error )

In my game on the Prisoner tab I don't have the option to "release" and "execute" the prisoners, and I saw this in my log, an error with harmony, can someone help me please.

**Comment by chboeh** [comment]
Getting the same error; offering my log file to assist.
[RimWorldErrorLog.txt](https://github.com/Aviuz/PrisonLabor/files/4786409/RimWorldErrorLog.txt)

**Comment by Hazzer** [comment]
@chboeh you have pretty messed up mod version. Do you use the latest version of mod?

**Comment by JacksonRoyal** [comment]
> @chboeh you have pretty messed up mod version. Do you use the latest version of mod?

it's been a while since I removed the mod and I was also waiting for a response, so I don't remember, but the link I posted says "PrisonLabor (0.10.7386.25884)"

**Comment by chboeh** [comment]
@Hazzer,

I've attempted to use the latest version although it just seems to break the InsipirationValue ability when moving from 1.1.2 to 1.1.7.

PrisonLabor Warning: InspirationTracker.GetInsipirationValue() didn't find map or pawn. Maybe it was called before calculating values.

Still fails on 1.1.7 ( doesn't add the scroll ability within the UX)
[RimWorldErrorLog.txt](https://github.com/Aviuz/PrisonLabor/files/4786566/RimWorldErrorLog.txt)

**Comment by Hazzer** [comment]
Do you guys have any ui mods?

**Comment by chboeh** [comment]
Only UI mod installed is RimHUD - https://rimworldbase.com/rimhud-mod/
I did install a UI mod to see if it'll fix it, RimThemes - https://rimworldbase.com/rimthemes-mod/

Didn't make an impact, removing or readding them.

Happy to use another UI mod if there is a suggestion.

**Comment by Hazzer** [comment]
@chboeh You can check if issue with "AddScrollToPrisonerTab3" appears in game without ui mods. I guess it's caused by mods patch incompatibility....

@JacksonRoyal Can you move prison labor mod below Core and Royalty in mod order list?

**Comment by chboeh** [comment]
@Hazzer 

Seems the GetInsiprationValue bug is by changing from old save, new games works fine when using 1.1.7

Still no scroll UI with game - ripped it down to limited requirements:

Initializing new game with mods:
  - brrainz.harmony
  - Ludeon.RimWorld
  - Ludeon.RimWorld.Royalty
  - avius.locks
  - avius.prisonlabor
Verse.Log:Message(String, Boolean)
Verse.Game:InitNewGame()
Verse.<>c:<Start>b__1_2()
Verse.LongEventHandler:RunEventFromAnotherThread(Action)
Verse.<>c:<UpdateCurrentAsynchronousEvent>b__27_0()
System.Threading.ThreadHelper:ThreadStart_Context(Object)
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object)
System.Threading.ThreadHelper:ThreadStart()

Does this only work with specific versions of RimWorld 1.1.2563(64) - Prevented updates for mods or HarmonyLib?

**Comment by JacksonRoyal** [comment]
@Hazzer 
I already tried to place it with priority, but without success

**Comment by Hazzer** [comment]
Ok so I checked the PL v1.1.7 with RW 1.1.2654 and no issue with AddScrollToPrisonerTab3. Checked on save from early RW 1.1. Whats you rimworld version?

**Comment by chboeh** [comment]
RimWorld 1.1.2563(64)

**Comment by chboeh** [comment]
Updated to the latest version - working now. Interesting.

**Comment by Hazzer** [comment]
No response from JacksonRoyal. Closed.
