### ISSUE TITLE
Prisoners attempt to do jobs in inaccessible locations

### ISSUE THREAD

**Issue by ZzZombo** [Aviuz/PrisonLabor#185]
Say, with Locks. This results in them Standing endlessly, until job priority changes their attempted job.

**Comment by Hazzer** [comment]
Do you use Common Sense mod?

**Comment by ZzZombo** [comment]
Yes, I do.

**Comment by Hazzer** [comment]
Common sense is incompatible with prison labor. And right now there is no plans to make them compatibile.
