### ISSUE TITLE
Prisoners do not rest to heal once they are capable of walking

### ISSUE THREAD

**Issue by ZzZombo** [Aviuz/PrisonLabor#186]
This slows their regeneration rate tremendously.

**Comment by Aviuz** [comment]
Do they have "Work" setting?

**Comment by ZzZombo** [comment]
Yes, they do.

**Comment by kbatbouta** [comment]
Do you have Dub performance... If you do, try taking a screen shot of the thinknode data.

**Comment by kbatbouta** [comment]
Do you have any mod that modify the rest or patient jobs? (and did you set the priority to manual or auto?)

**Comment by kbatbouta** [comment]
<img width="744" alt="Screen Shot 2020-06-14 at 3 34 01 PM" src="https://user-images.githubusercontent.com/6241020/84605732-7a443e00-ae54-11ea-953c-96571fd10f49.png">

Yeah by default it's not enabled.

**Comment by Aviuz** [comment]
> You can make time restrictions for prisoners.
> "Work" time will force them to work even when they're hungry or tired.
> "Joy" time will let them rest from job and get motivation bonus.
> "Sleep" time will force them to stay in prison cell.
> "Anything" is default setting.

Maybe it's not blatant obvious, but "Work" settings force prisoners to work even if they should heal

**Comment by Hazzer** [comment]
There is a option in mod menu which force prisoner to full rest. It can be turn on/off anytime during gameplay.
