### ISSUE TITLE
Consider the possibility of making prisoners first become colonists...

### ISSUE THREAD

**Issue by ZzZombo** [Aviuz/PrisonLabor#190]
That is, utilize the fact it's possible to imprison your own colonists, so make prisoners forced to work count as of the player faction. This makes them eligible for more jobs cleanly and avoid the majority of mod incompatibilities while introducing a few far less tricky issues of its own. Both benefits and downsides are no exhaustive.

The benefits are plentiful:

- They can now perform construction work in full, complete with hauling of resources to construction projects (fixes #135) and cleaning.
- You can see the destination of prisoners and progress of their tasks.
- Prisoners socialize.
- No more forbidden yield bugs.
- Mods compatibility: "Jobs of Opportunity (While You're Up)", "Pick Up And Haul", "PriorityClean". Most other mods that work specifically for the playable faction should also automatically be compatible.

Downsides I could think of:

- Faction relations. Example: raids on the player colony ordinarily will spare/save prisoners from their factions, but if made colonists they will be attacked. Can be solved perhaps by staging a revolt if there is a friendly raid going on, from this point prisoners of the matching faction(s) no longer count as colonists, and maybe even not as prisoners at all.
- Mods incompatibility: "PrisonerRansom" (can't easily demand ransom for prisoners if their faction changed).
- Need a clear way to tell genuine imprisoned colonists apart from captured outsiders.

Your thoughts?

**Comment by Hazzer** [comment]
Unfortunately changing prisoners faction to player faction breaks also vanilla prisoners options to release them etc.

**Comment by Aviuz** [comment]
Too much fuzz for me to be honest. It will require complete rewrite of game.
