### ISSUE TITLE
Mechanics overall and streamlining of internal processes

### ISSUE THREAD

**Issue by kbatbouta** [Aviuz/PrisonLabor#191]
Suggestions:

_1._ Rather than performing distance calculation for motivation, we simply check the rooms for wardens. This would allow us to use a single bool to indicate whether a warden is in the room or not and triggering auto escape for open areas.

_2._ Each room keep count of the prisoners and colonist which is way simpler than what is done now.

_3._ Armed colonist have motivation multiplier.

_4._ Only active wardens increase motivation. (Similar to when we were young and how we "pretended" to study for our bio class)

_5._ Motivation can be decreased by three ways: (in addition to the daily decay)

    a. No colonist in the room.
    b. Prisoners outnumber colonist and by a lot. (Weapon bonus can be a simple extra pawn of value so no need to keep count of anything else)
    c. Downed wardens (colonists) insight. 

Benefits:

_1._ No need to use single tick functions.
_2._ Only called on change. (push trigger rather than pull)
_3._ Can allow us to add surveillance system and other mechanics for more efficient non-volunteer work.

Notes:

In order to simulate the current warden mechanics, we simply make the warden more active (move more often). In the end the goal should be to have a system that doesn't need active management however if left without care would blow in your face.

We could use some props from the now dead simple slavery for a cosmetic makeover or even ask some of the prison architect artist for the camera sprites.

If you liked these ideas, or gave you some inspiration go ahead share your thoughts!

**Comment by Hazzer** [comment]
It may be abused if you have one really big room (eg 100x100) and your colonist/wardens doesnt stand near.

**Comment by kbatbouta** [comment]
We may define the warden capacity on a scale from 0.0 to 1.0 by

<img width="806" alt="Screen Shot 2020-06-16 at 9 10 51 AM" src="https://user-images.githubusercontent.com/6241020/84799572-4cc0d700-afb1-11ea-8155-97ecb37e6b15.png">

**Comment by kbatbouta** [comment]
> It may be abused if you have one really big room (eg 100x100) and your colonist/wardens doesnt stand near.

Thus for 100x100 it would require at least three guards for one prisoner only!

**Comment by Hazzer** [comment]
Overall idea is not stupid and I was thinking about something similar to make turrents as a motivation tool.

**Comment by kbatbouta** [comment]
Well, turrets are static so we can simply for each region the turret can hit do the calculations once and cache it. So we only monitor if the prisoner is in a covered region and if so add to his motivation the cached value. 

To account for multiple prisoners we simply cheat and decrease the guards count, while calculating the motivation, for said prisoners.  

The great thing is that the toils and jobs are already in place those all of this is easy to implement!

**Comment by Hazzer** [comment]
Still problem is with calculating amount of pawns in room.  So far didnt find any trigger for pawn entering room, so motivation as need will be called in every need_interval. Unless you know something which may help in implementation :P

**Comment by kbatbouta** [comment]
Doors!! The secret is in Region.IsDoorway  😎😎

**Comment by kbatbouta** [comment]
<img width="1680" alt="Screen Shot 2020-06-16 at 3 26 31 PM" src="https://user-images.githubusercontent.com/6241020/84834246-ce325c80-afe5-11ea-9dab-da97b8a8664e.png">

**Comment by Hazzer** [comment]
Ok, its a little problem when you have room layout like this:
![obraz](https://user-images.githubusercontent.com/4631961/84890352-946f5d80-b09a-11ea-875f-518a0f5ab346.png)
You cant tell to which room pawn will enter... but still searching

**Comment by kbatbouta** [comment]
Hmmm let me see if i can find my version of BetterPathFinding from b17 since i modified zehntar's implementation...

I'm kinda rusty since last time i modded rimworld was in b16 so let me check.

**Comment by kbatbouta** [comment]
However if the prisoners can pass through it then it's the same as an open area. We might be able to ignore 1x1 regions we 3 or more accessible edges.

**Comment by Hazzer** [comment]
Well I can extract from what room pawn come and almost have solution to get room where pawn is going. Some of that can be extracted from pawn path.

**Comment by kbatbouta** [comment]
Right, so the notify door will trigger a search over the pawns final destination (so we can avoid constantly running a watcher) then according to it we can update a region motivation value. And just to be safe we can add a slow (failsafe) watcher with seconds between runs similar to notifications.

**Comment by Hazzer** [comment]
Another corner case scenario:
When pawn stays in open doors, you draft him and move in other direction than first destination. Maybe we should stick with tick mechanic but dont calculate it every tick.

**Comment by kbatbouta** [comment]
hmmm. Interesting wanna setup some kind of experimental fork so we can test these ideas? And i can setup some check boxes and milestones for the initial planning...

**Comment by Hazzer** [comment]
I used my local branch to testing things :P

Another corner case: when prisoner is carried or e.g. put in cyro pod method getRoom return null. So checking after tick is still needed.
Also user case: user can have PL but not locks mod, checking if prisoner opens doors is meaningless because he will not call this method :D

**Comment by kbatbouta** [comment]
I might have an idea for tick scheduling however it will require me to check how unsafe can the code get before unity start screaming!!

Ok, i might have an idea that can help PL and others by performing some profiling while at runtime then throttling "unoptimized mods".

**Comment by kbatbouta** [comment]
Checkout my modifcation https://github.com/kbatbouta/PrisonLabor/tree/Inspiration-rework-patch-1

**Comment by kbatbouta** [comment]
@Hazzer Biggest performance improvement yet!! And been working on adding some features from psychology. However the i'm stuck on two things:
- Finding if a pawn have a weapon.
- Getting the pain value as displayed in UI rather than searching each body part for a headiff.

My changes (for now):
- Changed the execution frequency to only one prisoner per tick
- IsWatched can be triggered by interaction with the guards. 
- Prisoners will "gossip" ie: if one is in fear the others become motivated but treatment get trashed or if they know a guard like them they get less motivated and thus the player will need to maintain a neutral relations between wardens and prisoners.
- Any interaction between a guard and a prisoner trigger a runaway effect (added second level cumulative sum).

**Comment by kbatbouta** [comment]
Performance is so far great but rather get some help testing and balancing stuff.

**Comment by kbatbouta** [comment]
4 prisoners and 3 colonist
- 3x Speed
<img width="1680" alt="Screen Shot 2020-06-24 at 9 50 05 PM" src="https://user-images.githubusercontent.com/6241020
/85655682-ae91d880-b664-11ea-9ffb-c97f130f5305.png">

 - 1x Speed 
<img width="1680" alt="Screen Shot 2020-06-24 at 9 51 20 PM" src="https://user-images.githubusercontent.com/6241020/85656112-3d065a00-b665-11ea-9420-f7d1f68de650.png">

**Comment by kbatbouta** [comment]
<img width="676" alt="Screen Shot 2020-06-25 at 1 19 50 PM" src="https://user-images.githubusercontent.com/6241020/85791373-8fd42600-b6e6-11ea-9a4a-bfed67195723.png">

**Comment by kbatbouta** [comment]
<img width="785" alt="Screen Shot 2020-06-25 at 1 21 23 PM" src="https://user-images.githubusercontent.com/6241020/85791501-c5790f00-b6e6-11ea-8af1-f83d04f88b91.png">

**Comment by kbatbouta** [comment]
<img width="1680" alt="Screen Shot 2020-06-30 at 7 44 18 PM" src="https://user-images.githubusercontent.com/6241020/86207986-87378180-bb24-11ea-8a6a-48611871283f.png">
