### ISSUE TITLE
Bug: PrisonLabor Warning: InspirationTracker.GetInsipirationValue() didn't find map or pawn. Maybe it was called before calculating values.

### ISSUE THREAD

**Issue by Ashderpston** [Aviuz/PrisonLabor#194]
Log:
[Player.log](https://github.com/Aviuz/PrisonLabor/files/4858723/Player.log)

**Comment by Hazzer** [comment]
Please check if issue can be reproduce with only prison labor turned on. If no, it means mod incompatibility.

**Comment by Ashderpston** [comment]
A reinstall of harmony seemed to sort it
