### ISSUE TITLE
Lock Mod Compatibility for the new features

### ISSUE THREAD

**Issue by kbatbouta** [Aviuz/PrisonLabor#197]
Hope it will not mess with mod Locks and still works without mod

_Originally posted by @Hazzer in https://github.com/Aviuz/PrisonLabor/pull/195_

I've no idea how to detect other mods.

**Comment by Hazzer** [comment]
Check Quarry class. Its decection for Quarry mod.

**Comment by kbatbouta** [comment]
RESOLVED in https://github.com/kbatbouta/PrisonLabor/commit/ac9636cbe939069cc7a618c805eea67cb9d6ae16
