### ISSUE TITLE
[Performance Overhaul] AI Overhaul Help needed!

### ISSUE THREAD

**Issue by kbatbouta** [Aviuz/PrisonLabor#198]
**AI Overhaul** require:

- [x] **[High Priority]** Redo ```ThinkNode_Labor``` 
- [x] **[High Priority]** Refactor ```ThinkNode_Labor```
- [ ] Redo the prisoner ```Thinktree```  to a more simpler one.
- [x] Refactor ```WorkGiver_Supervise```.

**Escape mechanics** require:

- [ ] A total overhaul for the escape tracking.
- [x] Transition to a event/trigger based system.
- [ ] Leveraging vanilla escape system for prisoners.
**NOTE** Considering doing without the active escape tracking will improve performance significantly. 

_Originally posted by @kbatbouta in https://github.com/Aviuz/PrisonLabor/pull/195#issuecomment-656192777_

**Comment by Hazzer** [comment]
>[High Priority, Help Needed] Redo ThinkNode_Labor (We need caching but it's kinda messy)
What do you want to cache? Its similiar to vanilla `JobGiver_Work` and I prefer to stay that way.

> Redo the prisoner Thinktree to a more simpler one.
?

>Refactor WorkGiver_Supervise.
ok here maybe a little adjustment to new way.

**Comment by kbatbouta** [comment]
The vanilla one is not well written, and i want to cache the job search and scan results for the same tick.

**Comment by kbatbouta** [comment]
- [ ] ThinkNode_Labor lister things cache.
- [ ] Area_Labor based thing listing. 
- [ ] Area_Labor auto expanding to fill rooms.

**Comment by Hazzer** [comment]
>  Area_Labor auto expanding to fill rooms.

This one to remove. Even if its impacting perfomance.

>and i want to cache the job search and scan results for the same tick.

If I'm correctly, think tree is called once per tick. Every scanner generate results based on pawn, so its not called twice, right? How do you think it will be cached?

**Comment by kbatbouta** [comment]
Caching the scan result or perhaps the things list in the labor area to limit the search scope. Did without it by spreading the job search to the way vanilla does it by grouping ```WorkGiver```s to small groups at a time for a single tick thus never scanning for every type of job in a single tick.

Also the spike were (In the upstream/original code) because the code was copied from the compiler and just modified for the entire work list thus spiking to 15ms and even more.

**Comment by Hazzer** [comment]
The idea of prison labor is to forbid your colonists to do prisoners work. So if prisoner has access to place outside labor area it **_should be_** still consider in work scan as a place where prisoners and colonists can work at the same time.

**Comment by kbatbouta** [comment]
the labor area need to be in accordance with vanilla, used to control where some entity can access rather than being treated as a stockpile also the work scan is very slow hence trying to optimize it also if we don't use it this way then the locks mod is back as mandatory because it will create game play inconsistencies.

**Comment by kbatbouta** [comment]
The decisions i made were to avoid the current screenshots of the non optmized mod  
![Screen_Shot_2020-07-10_at_9 47 31_AM](https://user-images.githubusercontent.com/6241020/87179189-30077e80-c293-11ea-9acd-0491ff054bf6.png)
![Screen_Shot_2020-07-10_at_9 50 39_AM](https://user-images.githubusercontent.com/6241020/87179197-3269d880-c293-11ea-947a-18e89cd77798.png)
