### ISSUE TITLE
Prison work area not appearing in build list.

### ISSUE THREAD

**Issue by numbernegative** [Aviuz/PrisonLabor#200]
The tool to zone the prison labor work area is not appearing in the build list.
I'm aware of the warning on the workshop that says it might be hidden if there are too many other mods but as seen in the screenshot there is still plenty of room and I even removed a mod which cleared up 4 additional spots, but the prison labor zone is still not displayed.
From what I can tell the mod works fine otherwise, including the options in the prisoner interaction window.
![image](https://user-images.githubusercontent.com/11063321/87100955-4cfc6d00-c213-11ea-981a-1ef8da849969.png)

**Comment by 97Cweb** [comment]
Same issue for me, seems to be caused by Tiny Tweaks, as mentioned by 4D on the Prison Labor workshop page (29 Jun 8:53 pm). Disabling Tiny Tweaks makes it show back up

**Comment by numbernegative** [comment]
Yup, looks like that was it. Toyed with the Tiny Tweaks settings and couldn't figure out exactly what setting was causing the issue.

**Comment by 97Cweb** [comment]
Hopefully between the 2 mod groups, they can fix it. Making nightowls automatically sleep during day is must for me, along with making prisoners work in the quarry

**Comment by Hazzer** [comment]
Designators added in more common way since [v1.2.4](https://github.com/Aviuz/PrisonLabor/releases/tag/1.2.4).
