### ISSUE TITLE
Prisoners won't work (probably due to no allowed areas)

### ISSUE THREAD

**Issue by mikaelhogstrom** [Aviuz/PrisonLabor#202]
My prisoners will not work at all and I think it is because they don't have allowed areas. 
It is not possible to set this in the tab "Schedule"
![image](https://user-images.githubusercontent.com/1546869/87920299-4b377280-ca79-11ea-8cc5-fd73abe299ca.png)

I am on latest version of everything and only have PL mod and dependencies
![image](https://user-images.githubusercontent.com/1546869/87920502-981b4900-ca79-11ea-9c6d-c0dd263f46b0.png)

**Comment by Hazzer** [comment]
Try change anything to work in schedule for prisoners.

**Comment by mikaelhogstrom** [comment]
My bad, they were just being lazy bastards and I didn't have stone cutting turned on in the options which is what I was trying to get to work. They work "happily" now :)
