### ISSUE TITLE
Prison Labor not working along with Harmony?

### ISSUE THREAD

**Issue by Skyielle** [Aviuz/PrisonLabor#203]
Prison Labor suddenly stops working in my play through and this error was generated along with it.
https://gist.github.com/ae14e25511bfa17a757b54c5b13073e0
Something along with wrong null arguments Label 62, 63, and 64

**Comment by Hazzer** [comment]
Tested on latest steam version and its works fine (1.1.2654). I guess you are using unstable branch, right?

**Comment by Skyielle** [comment]
Ohhh okay, thanks for the solution. Yes I was using the unstable branch and tried to switch it on the stable version (1.1.2654). It now works, Thank you!
