### ISSUE TITLE
RimWorld (unstable) 1.2 Update

### ISSUE THREAD

**Issue by kbatbouta** [Aviuz/PrisonLabor#205]
The 1.2 now support multi-versioning so you can update it however (lucky PL is ready for the update with minimal work) only one patch broke and it require changing `Verse.Listing_Standard (30)` to `Verse.Listing_Standard (31)` in https://github.com/Aviuz/PrisonLabor/blob/1465bdd388c1721909631f2cd189c319f37fa9d1/Source/HarmonyPatches/Patches_GUI/GUI_Bill/Patch_BillCheckbox.cs#L71

**Comment by Hazzer** [comment]
Master should work now with version 1.2. Release will be probably tomorrow. Thanks.
