### ISSUE TITLE
"Work and Recruit" mode not recruiting

### ISSUE THREAD

**Issue by TSM-EVO** [Aviuz/PrisonLabor#211]
When a prisoner is on "work and recruit" there is no recruiting happening. When you switch over to just 'recruit' your warden will correctly recruit the prisoner.

**Comment by Hazzer** [comment]
Tested last night and I can reproduce the issue. Its take some time, but finally prisoner is recruited. However tested on core rimworld, prison labor, locks and bad people. Maybe you have other mods messing with recruitment?
