### ISSUE TITLE
Butcher Table

### ISSUE THREAD

**Issue by Apvalus** [Aviuz/PrisonLabor#214]
Hi, how to uninstall this mod, it ruins saves and becomes unstable after you recruit someone willingly. 

Also you cant butcher animals after some time.

**Comment by Hazzer** [comment]
Remove cuffs hediff by developer mode and then use mod option to remove data from save.

How it ruins save? Recruit by offer or event?

**Comment by Apvalus** [comment]
When u dissable mod, and load your save, Its everyhing grey.

**Comment by Hazzer** [comment]
Have you tried remove mod via Prison Labor mod option from option menu?

**Comment by Hazzer** [comment]
outdated
