### ISSUE TITLE
Fertile Fields mod: Prisoners do not construct soil.

### ISSUE THREAD

**Issue by soglasen666** [Aviuz/PrisonLabor#216]
As for Prison Labor v1.2.1. used with Fertile Fields mod
https://steamcommunity.com/sharedfiles/filedetails/?id=2012735237
prisoners do not build rich soil and do not terraform
https://raw.githubusercontent.com/soglasen666/bug-cases/main/0001/fertilefields1.png
https://raw.githubusercontent.com/soglasen666/bug-cases/main/0001/fertilefields2.png
https://raw.githubusercontent.com/soglasen666/bug-cases/main/0001/fertilefields3.png
although the job workType is common (Construction and Growing)
```xml
	<WorkGiverDef>
		<defName>ConstructFinishFramesTerraforming</defName>
		<label>transform terrain</label>
		<giverClass>RFF_Code.WorkGiver_ConstructFinishFramesTerraforming</giverClass>
		<workType>Construction</workType>
```
```xml
	<WorkGiverDef>
		<defName>ConstructFinishFramesGrowing</defName>
		<label>fertilize and plow soil</label>
		<giverClass>RFF_Code.WorkGiver_ConstructFinishFramesGrowing</giverClass>
		<workType>Growing</workType>
```
Mods installed:
```
Harmony
Core
Fertile Fields
Prison Labor
Royalty
```

**Comment by tophd7** [comment]
Try making a prisoner area over the soil. Construction seems to have been an issue making prisoners do it correctly

**Comment by soglasen666** [comment]
Placing a prison labor area over the soil did not make any difference:
https://github.com/soglasen666/bug-cases/blob/main/0001/fertilefields4.png

**Comment by Hazzer** [comment]
Its a compatibility issue. Imo fixing this is simpler from FF side. 
Quick look into source into WorkGiver_ConstructDeliverResourcesToBlueprintsTerraforming JobOnThing:
`            if (t.Faction != pawn.Faction)
            {
                return null;
            }
`
This one is blocking prisoners for doing thing. However prisoner which was a colonist should work. Simplest fix:
` if (t.Faction != pawn.Faction && !pawn.IsPrisonerOfColony)`

**Comment by samkester** [comment]
FF should now consider prisoners as valid pawns for all four farming/terraforming WorkGivers.

**Comment by Hazzer** [comment]
Nice! Closing issue :)

**Comment by soglasen666** [comment]
I've just tested new version of Fertile Fields with Prison Labor 1.2.1 and then with Prison Labor 1.2.2 but the issue didn't resolved. Probably the code is not the (only) cause of the bug? I've even tried to start a new game and this didn't hel either.

I'm afraid this issue should be reopened.

**Comment by Hazzer** [comment]
Yes, agains incorrect value are checked. This version should work. Teraforming at least works. 
[2012735237.zip](https://github.com/Aviuz/PrisonLabor/files/5937163/2012735237.zip)

**Comment by soglasen666** [comment]
@Hazzer 
Seems to work now, thanks!

@samkester 
Could you please take another look at it and integrate the code if it is valid? I guess these are the changes made in `\Source\Rainbeau's Fertile Fields\Work_Terraforming.cs`
```diff
147c147
<             if (t.Faction != pawn.Faction || (t.Faction == pawn.guest?.HostFaction && pawn.guest?.IsPrisoner == true))
---
>             if (t.Faction != pawn.Faction && !pawn.IsPrisonerOfColony)
204c204
<             if (t.Faction != pawn.Faction || (t.Faction == pawn.guest?.HostFaction && pawn.guest?.IsPrisoner == true))
---
>             if (t.Faction != pawn.Faction && !pawn.IsPrisonerOfColony)
243c243
<             if (t.Faction != pawn.Faction || (t.Faction == pawn.guest?.HostFaction && pawn.guest?.IsPrisoner == true))
---
>             if (t.Faction != pawn.Faction && !pawn.IsPrisonerOfColony)
307c307
<             if (t.Faction != pawn.Faction || (t.Faction == pawn.guest?.HostFaction && pawn.guest?.IsPrisoner == true))
---
>             if (t.Faction != pawn.Faction && !pawn.IsPrisonerOfColony)
```

I love both of your mods they make the game so much better. Thank you for keeping it up!

**Comment by samkester** [comment]
Yep, that was my fault. Got turned around with my boolean logic - wrote the condition when the job should be accepted, but I needed the condition when the job should be rejected. This is why I shouldn't late-night code <.<

I've pushed another update, let me know if it's still broken.

**Comment by soglasen666** [comment]
@samkester 
I've synchronized "Fertile Fields" with steam version and everything seems to work fine, thanks! I will inform you in case if something will go wrong.
