### ISSUE TITLE
Colonist dont respect prisoners Jobs

### ISSUE THREAD

**Issue by Aldehyt** [Aviuz/PrisonLabor#22]
Sometimes colonist dont respect prisoners jobs, and in my example i use "Hardcore SK modpack" when prisoner cutting wood logs to plank, colonist take a wood from sawmill during prisoner job, and they can endlessy looping.

**Comment by Aviuz** [comment]
i think It depends on [same bug](https://github.com/Aviuz/PrisonLabor/issues/23)
