### ISSUE TITLE
Dubs Bad Hygiene mod: Prisoners do not refill passive coolers and wash tubs.

### ISSUE THREAD

**Issue by soglasen666** [Aviuz/PrisonLabor#220]
As for Prison Labor (ver. 1.2.2 @ github) used with Dubs Bad Hygiene (ver. 12 Dec, 2020 @ 11:21 am)
https://steamcommunity.com/sharedfiles/filedetails/?id=836308268
prisoners do not refill passive coolers and wash tubs while having access to a water source
https://raw.githubusercontent.com/soglasen666/bug-cases/main/0002/dubsbadhygiene1.png
https://raw.githubusercontent.com/soglasen666/bug-cases/main/0002/dubsbadhygiene2.png
https://raw.githubusercontent.com/soglasen666/bug-cases/main/0002/dubsbadhygiene3.png
When I put a door colonist does this job
https://raw.githubusercontent.com/soglasen666/bug-cases/main/0002/dubsbadhygiene4.png
https://raw.githubusercontent.com/soglasen666/bug-cases/main/0002/dubsbadhygiene5.png
https://raw.githubusercontent.com/soglasen666/bug-cases/main/0002/dubsbadhygiene6.png

Probably the problem is related to change in passive coolers (fuel becomes water instead of wood) and somehow with the water refilling job itself.

Mods installed:
```
Harmony (ver. 30 Jul, 2020 @ 1:04pm)
Core 
Dubs Bad Hygiene (ver. 12 Dec, 2020 @ 11:21am)
Prison Labor (ver. 1.2.2 @ github)
Royalty [Official DLC]
```

**Comment by Hazzer** [comment]
Again - Dubs mod is writen no prisoner wise. Not gonna fix that by my side because it require rewrite his classes. As I can see from decompiled .dll case its similar to: https://github.com/Aviuz/PrisonLabor/issues/216

**Comment by soglasen666** [comment]
Created an issue at https://github.com/Dubwise56/Dubs-Bad-Hygiene/issues/48
