### ISSUE TITLE
Seeds Please: Minor compatability bug

### ISSUE THREAD

**Issue by BlaeWulf** [Aviuz/PrisonLabor#221]
When prisoners harvest, the produce is automatically forbidden while seeds are allowed. Colonists harvest as intended and this only effects prisoners.

by-products from other mods such as plant scraps from fertile fields are not effected.
Produce from both vanilla plants and mods such as VGP are also forbidden when harvested from prisoners.

I attempted to re-add the SeedsPlease patch that was removed in Prison Labour 1.1.6 to see if that fixed it, but I had trouble compiling and I couldn't see any reference to harvesting, only sowing, so I assume that wouldn't have fixed it anyway?

Edit: Sorry forgot to say;

Produce is forbidden in both grow zones and hydroponics.

I've tested with only these mods, and PL both above and below SP, and the bug is still reproducible. and the grow zones / hydroponics are in the labour area and home zone.

**Comment by Hazzer** [comment]
Have you checked with the latest github version?  I added some compatibility patch here: https://github.com/notfood/RimWorld-SeedsPlease/blob/master/Source/JobDriver_PlantWorkWithSeeds.cs

**Comment by BlaeWulf** [comment]
Hazzer, thanks for the reply, and thanks for adding the compatibility. This was just me being silly, I had local mods folders for both mods, so updated them from github before I made the mod report, but hadn't checked what was loaded and RimWorld was still loading SeedsPlease from steam. It's working perfectly now.

Sorry for the false bug report, I saw PL had a similar bug previously and thought it would have been related to that.

I'll "close with comment" i'm new to github so if you need me to mark it as fixed or anything please let me know!
