### ISSUE TITLE
Prisoners keep eating meals they're not supposed to.

### ISSUE THREAD

**Issue by RobRoseKnows** [Aviuz/PrisonLabor#222]
I'm using Vanilla Cooking Expanded and my prisoners keeps eating all of my Gourmet meals even though their meal plan is only set to fine meals by default. Are prisoners deliberately disobeying their meal plan, and if so, can you add a mod setting to turn that off?

**Comment by RobRoseKnows** [comment]
Ah yeah, that would be great. I'd love to submit a PR, but I'm not too familiar with Rimworld modding yet.

**Comment by Hazzer** [comment]
Implemented in https://github.com/Aviuz/PrisonLabor/releases/tag/1.3.10. Closed.
