### ISSUE TITLE
Fail to reserve target (Toils)

### ISSUE THREAD

**Issue by Aldehyt** [Aviuz/PrisonLabor#23]
Prisoners and colonists sometimes trying use benches, at the same time.

Edited:
On screen, prisoner and colonist digging same square
![image](https://user-images.githubusercontent.com/24838724/28245332-619d000e-6a04-11e7-9e09-fdb9088e0fe3.png)

 Or Cutting at the same time:

![image](https://user-images.githubusercontent.com/24838724/28245381-7b03e7aa-6a05-11e7-945f-0219968818e5.png)

**Comment by Aviuz** [comment]
They can't failing at reservation target i think. Will look at it. Thanks!

**Comment by Aviuz** [comment]
Hmm it's look like compatibility bug. I need list of your mods.

**Comment by Aldehyt** [comment]
![image](https://user-images.githubusercontent.com/24838724/28247323-500bfa5a-6a2e-11e7-8019-59e6951a6292.png)
![image](https://user-images.githubusercontent.com/24838724/28247325-5a6643d4-6a2e-11e7-9bdd-0a5f0983e676.png)
![image](https://user-images.githubusercontent.com/24838724/28247331-69e44a68-6a2e-11e7-90f8-2aff26ad06b3.png)

Here you go.

**Comment by Aviuz** [comment]
> So I'm experiencing the issue where prisoners work on the same jobs as colonists, here is my active mod list (in order)
>
>Hubs Lib
Miscallaneous Core
Misc Robots
Misc Robots++
Prison Labor(Alpha)
SS Cultivator Tools
EPOE 2.0 preview
More Furniture (A17)
More Trade Ships
Expanded Prosthetics and Organ Engineering
Medical Tab
Prisoner Harvesting
Remote Explosives
Misc. MapGen FactionBase
EdB Prepare Carefully
ET Fuse
Highway Restoration
[RF] Basic Bridges (and Fishing) [a17]
Refugee Stats (A17)
Wanderer Stat
ED- Embrasures 
Quarry
Simple Sidearms
Combat Extended
RimSearch
WM Reuse Pods
Herbal Boosters
Phycology
Pawns Play Together
Prisoner Joy
>
>Oh I forgot to write that I have refactored work priorities installed right after combat extended
>
>I have a feeling that might be the problomatic mod

**Comment by Aviuz** [comment]
>Not a conflict but a minor bug, seems the Hauling bots from Misc robots++ try to haul away items a prisoner is smelting at the Electric Smelter.
>
>EDIT2: Not just the bots that do it, pawns try to take the weapons away as well, only seems to happen for the Electric Smelter, left them working in peace on the mending bench I have.
>
>Also noticed sometimes my pawns getting into a loop of dropping food for a prisoner then immediately picking it back up in an endless cycle unless I recruit them or they get tired/hungry and just eat the meal themselves. Not sure what would be causing that, maybe one of the numerous mods I have that change work priorities/add new ones.
>
>EDIT: Can give my modlist if you want but it's 146 mods currently..

>HugsLib | http://steamcommunity.com/sharedfiles/filedetails/?id=818773962
JecsTools | http://steamcommunity.com/sharedfiles/filedetails/?id=932008009
Miscellaneous 'CORE' | http://steamcommunity.com/sharedfiles/filedetails/?id=704181221
Mod List Backup | http://steamcommunity.com/sharedfiles/filedetails/?id=840043916
RuntimeGC | http://steamcommunity.com/sharedfiles/filedetails/?id=962732083
Pandora Dark | 
Misc. Robots | http://steamcommunity.com/sharedfiles/filedetails/?id=724602224
Misc. Robots++ | http://steamcommunity.com/sharedfiles/filedetails/?id=747645520
Misc. MapGenerator | http://steamcommunity.com/sharedfiles/filedetails/?id=704182588
Misc. MapGen FactionBase | http://steamcommunity.com/sharedfiles/filedetails/?id=821655202
Misc. Training | http://steamcommunity.com/sharedfiles/filedetails/?id=717575199
Star Wars - The Force | http://steamcommunity.com/sharedfiles/filedetails/?id=918226861
Star Wars - Fully Functional Lightsabers | http://steamcommunity.com/sharedfiles/filedetails/?id=918200645
Star Wars - Factions | http://steamcommunity.com/sharedfiles/filedetails/?id=918227266
Call of Cthulhu - Industrial Age | http://steamcommunity.com/sharedfiles/filedetails/?id=777197241
More Faction Bases | http://steamcommunity.com/sharedfiles/filedetails/?id=933541240
More vanilla factions | http://steamcommunity.com/sharedfiles/filedetails/?id=830221184
More Trade Ships | http://steamcommunity.com/sharedfiles/filedetails/?id=725465444
Wealthy Traders | http://steamcommunity.com/sharedfiles/filedetails/?id=932857483
Faction Discovery | http://steamcommunity.com/sharedfiles/filedetails/?id=751841890
Auto Seller | http://steamcommunity.com/sharedfiles/filedetails/?id=725952961
[sd] advanced powergeneration | http://steamcommunity.com/sharedfiles/filedetails/?id=760088748
[sd] goodnight | http://steamcommunity.com/sharedfiles/filedetails/?id=763943290
[T] MoreFloors | http://steamcommunity.com/sharedfiles/filedetails/?id=725623521
Apparello 2 | http://steamcommunity.com/sharedfiles/filedetails/?id=728381322
Bridgello | http://steamcommunity.com/sharedfiles/filedetails/?id=932124891
ConcreteWalls | http://steamcommunity.com/sharedfiles/filedetails/?id=795240891
DDA Security and More | http://steamcommunity.com/sharedfiles/filedetails/?id=892434137
Disassemble Shield Belt | http://steamcommunity.com/sharedfiles/filedetails/?id=852712460
Dryxsteel | http://steamcommunity.com/sharedfiles/filedetails/?id=917057191
Dubs Rimkit | http://steamcommunity.com/sharedfiles/filedetails/?id=832333531
Efficient Light | http://steamcommunity.com/sharedfiles/filedetails/?id=727862986
FashionRIMsta | http://steamcommunity.com/sharedfiles/filedetails/?id=745193823
Feed The Colonists | http://steamcommunity.com/sharedfiles/filedetails/?id=729690064
Herbal Boosters | http://steamcommunity.com/sharedfiles/filedetails/?id=962926505
Invisible Conduits | http://steamcommunity.com/sharedfiles/filedetails/?id=971868628
LT-DoorMat | http://steamcommunity.com/sharedfiles/filedetails/?id=727309536
Mending | http://steamcommunity.com/sharedfiles/filedetails/?id=735241897
MinifyEverything | http://steamcommunity.com/sharedfiles/filedetails/?id=872762753
More Furniture (A17) | http://steamcommunity.com/sharedfiles/filedetails/?id=929270780
More Vanilla Turrets | http://steamcommunity.com/sharedfiles/filedetails/?id=730528968
MT - Silent Doors | http://steamcommunity.com/sharedfiles/filedetails/?id=933010556
No Debris | http://steamcommunity.com/sharedfiles/filedetails/?id=953263771
Pawns Play Poker | http://steamcommunity.com/sharedfiles/filedetails/?id=927867598
Quarry | http://steamcommunity.com/sharedfiles/filedetails/?id=942690136
Realistic Rooms | http://steamcommunity.com/sharedfiles/filedetails/?id=848972794
Reasonable Components | http://steamcommunity.com/sharedfiles/filedetails/?id=944063011
Realistic Smokeleaf | http://steamcommunity.com/sharedfiles/filedetails/?id=963900121
RedistHeat | http://steamcommunity.com/sharedfiles/filedetails/?id=969427810
RimHair Styles Merged | http://steamcommunity.com/sharedfiles/filedetails/?id=839849806
Facial Stuff 0.17.1.2 | http://steamcommunity.com/sharedfiles/filedetails/?id=818322128
Roof Support A17 | http://steamcommunity.com/sharedfiles/filedetails/?id=932136308
RT Fuse | http://steamcommunity.com/sharedfiles/filedetails/?id=728314182
RT's Weapon Pack | http://steamcommunity.com/sharedfiles/filedetails/?id=730899625
Travel rations: MREs | http://steamcommunity.com/sharedfiles/filedetails/?id=838360846
Tribal Essentials Modpack | http://steamcommunity.com/sharedfiles/filedetails/?id=928716116
Jecs Everlasting Apparel | http://steamcommunity.com/sharedfiles/filedetails/?id=909429482
Infused | http://steamcommunity.com/sharedfiles/filedetails/?id=731287727
Outfitter 0.17.1.4 | http://steamcommunity.com/sharedfiles/filedetails/?id=738206572
Outfitter A17 - Infused | http://steamcommunity.com/sharedfiles/filedetails/?id=738208470
Super Soil | http://steamcommunity.com/sharedfiles/filedetails/?id=823626435
Tilled Soil | http://steamcommunity.com/sharedfiles/filedetails/?id=725747149
Vegetable Garden  | http://steamcommunity.com/sharedfiles/filedetails/?id=932240696
Plant saver veg garden | http://steamcommunity.com/sharedfiles/filedetails/?id=738403627
Blueprints | http://steamcommunity.com/sharedfiles/filedetails/?id=708455313
RazzleDazzle | http://steamcommunity.com/sharedfiles/filedetails/?id=935948631
[A17] Divided Growing Tasks | http://steamcommunity.com/sharedfiles/filedetails/?id=951991605
[A17] Nurse Job Mod | http://steamcommunity.com/sharedfiles/filedetails/?id=953903557
[A17] Trading Spot | http://steamcommunity.com/sharedfiles/filedetails/?id=948572545
Additional Traits v2.2 [A17 Update] | http://steamcommunity.com/sharedfiles/filedetails/?id=946944965
Extended traits | http://steamcommunity.com/sharedfiles/filedetails/?id=930207055
Psychology | http://steamcommunity.com/sharedfiles/filedetails/?id=959814527
Billy's Improved Caravan Formation | http://steamcommunity.com/sharedfiles/filedetails/?id=953429016
Billy's Improved Load Transport Pods | http://steamcommunity.com/sharedfiles/filedetails/?id=960731735
Colony Manager | http://steamcommunity.com/sharedfiles/filedetails/?id=715565262
Cooks Can Refuel | http://steamcommunity.com/sharedfiles/filedetails/?id=781383672
Crazy Crafting Obsession | http://steamcommunity.com/sharedfiles/filedetails/?id=954328761
Gas Trap | http://steamcommunity.com/sharedfiles/filedetails/?id=964388988
Hand Me That Brick | http://steamcommunity.com/sharedfiles/filedetails/?id=776679895
Hunting Alert | 
I Can Fix It! | http://steamcommunity.com/sharedfiles/filedetails/?id=817231829
Jecs Hunting with Traps | http://steamcommunity.com/sharedfiles/filedetails/?id=960099879
JTBetterCrashedShips | http://steamcommunity.com/sharedfiles/filedetails/?id=948015480
JTDrill5Eva | http://steamcommunity.com/sharedfiles/filedetails/?id=948033571
JTMoreHydroponicOptions | http://steamcommunity.com/sharedfiles/filedetails/?id=948049082
JTReplaceWalls [A17] | http://steamcommunity.com/sharedfiles/filedetails/?id=936562361
JTZoneButtons | http://steamcommunity.com/sharedfiles/filedetails/?id=940385954
Large Map Save Game Fix | http://steamcommunity.com/sharedfiles/filedetails/?id=876729369
LongRangePodLauncher | http://steamcommunity.com/sharedfiles/filedetails/?id=819435604
Mad Skills | http://steamcommunity.com/sharedfiles/filedetails/?id=731111514
Markers | 
More Planning | http://steamcommunity.com/sharedfiles/filedetails/?id=881100382
Notifications Archiver | http://steamcommunity.com/sharedfiles/filedetails/?id=952232391
Packified Animals | http://steamcommunity.com/sharedfiles/filedetails/?id=823134509
Patch - Storage Search + AllowFresh A17 | http://steamcommunity.com/sharedfiles/filedetails/?id=771073854
Path Avoid - A17 | http://steamcommunity.com/sharedfiles/filedetails/?id=935210992
Patient Sanity | 
Plant Cutting is for Growers! | http://steamcommunity.com/sharedfiles/filedetails/?id=832245101
P-Music | http://steamcommunity.com/sharedfiles/filedetails/?id=725130005
Preset Filtered Zones | http://steamcommunity.com/sharedfiles/filedetails/?id=953046214
PrisonerRansom | http://steamcommunity.com/sharedfiles/filedetails/?id=794038005
QualityBuilder | http://steamcommunity.com/sharedfiles/filedetails/?id=754637870
Quality Cooldown | http://steamcommunity.com/sharedfiles/filedetails/?id=926675929
Reverse Commands | http://steamcommunity.com/sharedfiles/filedetails/?id=858744731
Set-Up Camp | http://steamcommunity.com/sharedfiles/filedetails/?id=932951772
Simple sidearms | http://steamcommunity.com/sharedfiles/filedetails/?id=927155256
Haul to Stack | http://steamcommunity.com/sharedfiles/filedetails/?id=949498803
Stack Merger | http://steamcommunity.com/sharedfiles/filedetails/?id=857164561
Stack XXL | http://steamcommunity.com/sharedfiles/filedetails/?id=826366050
Storage Search A17 | http://steamcommunity.com/sharedfiles/filedetails/?id=726479594
Veinminer | http://steamcommunity.com/sharedfiles/filedetails/?id=944099898
Scaling Roads | http://steamcommunity.com/sharedfiles/filedetails/?id=953262068
Allow Tool | http://steamcommunity.com/sharedfiles/filedetails/?id=761421485
AllowDeadMansApparel | http://steamcommunity.com/sharedfiles/filedetails/?id=879105471
Area Unlocker | http://steamcommunity.com/sharedfiles/filedetails/?id=725153576
Better Workbench Management | http://steamcommunity.com/sharedfiles/filedetails/?id=935982361
CleaningArea | http://steamcommunity.com/sharedfiles/filedetails/?id=870089952
Combat Readiness Check | http://steamcommunity.com/sharedfiles/filedetails/?id=941884273
Conduit Deconstruct | http://steamcommunity.com/sharedfiles/filedetails/?id=838336462
Copy Allowed Area | http://steamcommunity.com/sharedfiles/filedetails/?id=972553000
Follow Me | http://steamcommunity.com/sharedfiles/filedetails/?id=715759739
JTExport | http://steamcommunity.com/sharedfiles/filedetails/?id=939614291
Medical Tab | http://steamcommunity.com/sharedfiles/filedetails/?id=715565817
Moody | http://steamcommunity.com/sharedfiles/filedetails/?id=826998327
MT - Starting Tech | http://steamcommunity.com/sharedfiles/filedetails/?id=932251222
Numbers | http://steamcommunity.com/sharedfiles/filedetails/?id=939597551
Realistic Darkness Lighter Version V3.0 A17 | http://steamcommunity.com/sharedfiles/filedetails/?id=745800936
Relations Tab | http://steamcommunity.com/sharedfiles/filedetails/?id=709317151
ResearchPal | http://steamcommunity.com/sharedfiles/filedetails/?id=946390822
See Deep Ores | http://steamcommunity.com/sharedfiles/filedetails/?id=949894479
Table Diner | 
Recon And Discovery | http://steamcommunity.com/sharedfiles/filedetails/?id=935948526
Crash Landing | http://steamcommunity.com/sharedfiles/filedetails/?id=730384702
More Manhunters | http://steamcommunity.com/sharedfiles/filedetails/?id=755689464
Prison Labor (Alpha) | http://steamcommunity.com/sharedfiles/filedetails/?id=972057888
Sometimes Raids Go Wrong | http://steamcommunity.com/sharedfiles/filedetails/?id=936742413
Defensive Positions | http://steamcommunity.com/sharedfiles/filedetails/?id=761219125
A Dog Said... | http://steamcommunity.com/sharedfiles/filedetails/?id=746425621
Harvest Everything! | http://steamcommunity.com/sharedfiles/filedetails/?id=934666843
Expanded Prosthetics and Organ Engineering 2.0 | https://ludeon.com/forums/index.php?topic=10571.0
DE Surgeries | 
EPOE + DE Surgery Bone Fix | http://steamcommunity.com/sharedfiles/filedetails/?id=836916859
Mod Medicine Patch | 
GHXX Tech Advancing | http://steamcommunity.com/sharedfiles/filedetails/?id=735268789
Hospitality | http://steamcommunity.com/sharedfiles/filedetails/?id=753498552

**Comment by Aviuz** [comment]
fixed in 0.8
