### ISSUE TITLE
Prisoners don't clean

### ISSUE THREAD

**Issue by Aldehyt** [Aviuz/PrisonLabor#24]
![image](https://user-images.githubusercontent.com/24838724/28245294-c5f74132-6a03-11e7-838e-57fdf9eea919.png)

Like on screen, prisoner wandering, but he can clean blood and dirt after mining

**Comment by Aviuz** [comment]
Weird. Are you sure prisoner have checked cleaning, and dirt etc. is in home area, prisoner is fed?

**Comment by Aldehyt** [comment]
![image](https://user-images.githubusercontent.com/24838724/28247370-237c00a6-6a2f-11e7-8d55-abc724ccd161.png)
![image](https://user-images.githubusercontent.com/24838724/28247371-2a6b9200-6a2f-11e7-8aaf-de3f29950fd0.png)

**Comment by Aldehyt** [comment]
I hope many images are not a problem ? :)

**Comment by Aviuz** [comment]
No, it's not.
Weird, all of your prisoners refusing to clean?

**Comment by Aldehyt** [comment]
Yes, 
before i tried your mod with worktab, but this wont work, so i disabled worktab, huntsman was catched, after mod changes

**Comment by Aviuz** [comment]
Thank you. You can always [download](https://github.com/Aviuz/PrisonLabor/releases) older version.

**Comment by Aviuz** [comment]
fixed in 0.7
