### ISSUE TITLE
Constant errors while mod running

### ISSUE THREAD

**Issue by myth-heart** [Aviuz/PrisonLabor#241]
Possibly an incompatibility but haven't been able to figure out what. Errors only started after I set it to allow all work types; prisoners weren't working prior to that but no errors.

Log: https://gist.github.com/367dd2d69460cc59924631aa789cb211

**Comment by Hazzer** [comment]
It should be fixed in latest version: https://github.com/Aviuz/PrisonLabor/releases/tag/1.3.3 . Thanks for reporting.
