### ISSUE TITLE
Failing to reserve food

### ISSUE THREAD

**Issue by Aviuz** [Aviuz/PrisonLabor#25]
Sometimes wardens fail to reserve a food delivered to prisoner.
When?
Why?

**Comment by Aldehyt** [comment]
When prisoner is hungry and wandering around, he "cant see food dropped by warden", then warden looping, pick uping, and dropping food

**Comment by Aviuz** [comment]
yes but it does not match all cases, it's something different

**Comment by Aldehyt** [comment]
This look like warden with his job, dont want wait for end prisoner job

**Comment by Aviuz** [comment]
In most cases this works. After dropping food he should reserve this food. Warden shouldn't bring food to prisoners who can reach food. Even if he still thinking that food is need to be brought, warden shouldn't touch reserved food.

**Comment by Aldehyt** [comment]
Ok understand, btw where we can write suggestion ? i dont want clutter here.

**Comment by Aviuz** [comment]
http://steamcommunity.com/workshop/filedetails/discussion/972057888/2217311444324340978/

**Comment by Aviuz** [comment]
fixed in 0.5a

**Comment by Aviuz** [comment]
I think I fixed it for good in 0.7
