### ISSUE TITLE
Prisoners not registering at all for this mod set

### ISSUE THREAD

**Issue by fobillay** [Aviuz/PrisonLabor#43]
No errors in the De-bug log coming up related to this mod, and the mod is not working what so ever. I checked the tutorials and im doing everything right.

heres the log: https://gist.github.com/59e23d7af08170cc90c5211630eec62e

Great looking mod btw, is there any way u can make it to where the beta wont break the save game?

**Comment by Aviuz** [comment]
@fobillay Thank you for reporting. I will look at this later, but it seems the mod didn't even load, so it's probably something else.

Mod won't break saves if put to "disabled" state. It's planned for 0.7 and you can track it [here](https://github.com/Aviuz/PrisonLabor/issues/37)

**Comment by fobillay** [comment]
I pushed the mod up to near the top of the order, this time i checked and the prisoners are not coming up on the work tab, but they do have a motivation bar on their needs tab, on the intial screen it of starting rimworld it has says the mod is loaded on the debug log, but it when i start the save i didnt find it.

**Comment by Aviuz** [comment]
@fobillay In order to force prisoners to work you must check "Force to work" option in prisoner interaction menu ("Prisoner" tab). Even then he can refuse to work on several conditions which are described for example in mod description or tuorial.

**Comment by fobillay** [comment]
i watched the tutorial and was not aware of the update, problem solved, i however did start getting this error about a null reference once they started working


https://gist.github.com/a9fda545fb2a8e0ac71c68239651c1ff

**Comment by Aviuz** [comment]
It's from psychology mod

**Comment by fobillay** [comment]
welp just tested it for a bit and everything is running fine, there is a bit of an issue with colonists dropping food off, then picking it up, then dropping, and repeating, the only way to fix is to forbid the food, but other than that its working like a charm, thanks man

**Comment by Aviuz** [comment]
about that I'm aware of that, but because it happens very rare I will fix it when other more important problems are resolved.
