### ISSUE TITLE
Compatibility Issue with SeedsPlease Mod

### ISSUE THREAD

**Issue by TinkerObi** [Aviuz/PrisonLabor#50]
I'm using SeedsPlease mod and with PrisonLabor normal pawns will plant seeds in growing zones. However prison pawns will bypass the seeds and grow without. (I think both mods are great)

No errors in logs, prisoners just bypass the requirement

**Comment by Aviuz** [comment]
Fixed, but forbidden bug is duplicated here as well. It will work but with forbidden crops.

TODO: copy fix from original fragment to SeedsPlease fix

**Comment by Aviuz** [comment]
fixed in 0.8 (that was hard one :D)

**Comment by notfood** [comment]
It broke for B18 and I'm not sure what broke.

I can add a method you can prefix in an easier way. Just tell me what your mod requires and I'll add it.

**Comment by Aviuz** [comment]
This is already fixed on 0.9.2
