### ISSUE TITLE
Harvested crops default to forbidden

### ISSUE THREAD

**Issue by JB-pythonic-py** [Aviuz/PrisonLabor#54]
When forced laborers harvest crops, the generated harvest defaults to forbidden and has to be manually changed before pawns can move the harvested crop.  I'll try to test this with certain mods disabled to be sure it's not a mod conflict.

**Comment by Aviuz** [comment]
fixed in 0.8

**Comment by JB-pythonic-py** [comment]
When is it going to be updated to 0.8 on the Steam Workshop?

**Comment by Aviuz** [comment]
@JB-pythonic-py Currently there is a dev version being tested by volunteers. I need to finish two more features to finish 0.8: revolts and prisoner joy.

**Comment by JB-pythonic-py** [comment]
Thanks for the update.
