### ISSUE TITLE
Allow to remove the restraints

### ISSUE THREAD

**Issue by mibac138** [Aviuz/PrisonLabor#58]
Currently the prisoners are kind of slow due to restraints. I think an option to remove them should exist. It would remove the debuff(s?) of them at the possible cost of a possibility of escaping or stealing some guns from the armory (as removing the restraints would allow opening doors) and doing revolts.

**Comment by Aviuz** [comment]
Good idea, I would think about it. There are few aspects that need consideration:
- prisoners should be "worse" workers
- it's deep inside RimWorld code (dunno why, but it is), and I've already done 22 transpillers (that's a lot)
- prisoners break chains while escaping anyway, and stealing guns from armory etc. is like month of programming

**Comment by mibac138** [comment]
> prisoners should be "worse" workers
Maybe the impact of motivation on work speed could be increased?
> stealing guns from armory etc. is like month of programming
I did not realize the amount of complexity this requires. There should be some other drawbacks though but at the moment I'm out of ideas.

Side note: why do you consider transpilers bad? 22 doesn't seem like too much. As far as I know they run once and that's it so there's no real speed penalty except startup, right?

**Comment by Aviuz** [comment]
Yes, but they can work differently depending on others mod. Some of them are very safe like semi-Postfixes, semi-Prefixes, but some of them are very sensitive on particular parts. It's last thing I should do to change something.

I didn't see a single mod with 10+ transpillers.

But when comes to performance yes, they are startup single-runners.

**Comment by Aviuz** [comment]
https://github.com/Aviuz/PrisonExpansion/issues/5
