### ISSUE TITLE
Pawns don't complete Priority tasks

### ISSUE THREAD

**Issue by Evilbohdran** [Aviuz/PrisonLabor#59]
When assigning a priority task to a pawn (like build a wall), they do the first step (bring bricks) then immediately wander off to do something else. This is true for all priority tasks (told a pawn to butcher creatures, they did it once then wandered off). Started a new colony that exhibited this behavior, then disabled the mod and restarted another colony and pawn behaved as normal (finished building that wall section). 

Tested this with just HugsLib and Prison Labor installed.

**Comment by Aviuz** [comment]
You mean COLONISTS dont do priority task?

**Comment by Aviuz** [comment]
Ok I've managed to reproduce error

**Comment by Aviuz** [comment]
fixed in 0.8.3
