### ISSUE TITLE
JoyGivers "debris"

### ISSUE THREAD

**Issue by refugeedrone** [Aviuz/PrisonLabor#63]
this error has been poping up on me
[bug report.txt](https://github.com/Aviuz/PrisonLabor/files/1351107/bug.report.txt)

**Comment by Aviuz** [comment]
oh i remeber that error. Its from joy testing. Did I forgot to remove that???

It will gappen only if prisoner is on joy time btw. (if you want to avoid this before fix)

**Comment by refugeedrone** [comment]
I can confirm  the prisoner wasn't set up for joy time. Also I did unsubscribe/resubscribed  to confirm  I had the most recent  patch.

**Comment by Aviuz** [comment]
Hmm okay i will fix this today

**Comment by refugeedrone** [comment]
Good looking out. Thanks

**Comment by Aviuz** [comment]
fixedin 0.8.6
