### ISSUE TITLE
Labor area doesn't work with sowing

### ISSUE THREAD

**Issue by Maldaris** [Aviuz/PrisonLabor#64]
After setting up a section of grow zones inside of a prisoner labor zone, my colonists still insist on sowing the grow zones. Prisoners work the grow zones in tandem, so it's not completely broken, just diverts my high level farmers from the higher skill requirement crops.

**Comment by Aviuz** [comment]
Hmm weird I was checking that when releasing feature. Ill check it, thanks :)

**Comment by Aviuz** [comment]
bug confirmed

**Comment by Aviuz** [comment]
fixed in 0.8.6
