### ISSUE TITLE
Bill "Details" Screen is Blank

### ISSUE THREAD

**Issue by Pascal125** [Aviuz/PrisonLabor#76]
When opening the "Details" screen of any production table/construct, the screen is blank. 
![ss 2017-12-01 at 06 19 49](https://user-images.githubusercontent.com/24816113/33480810-fd317fa0-d65f-11e7-8e24-429ab5edbf37.jpg)

The problem began occuring for me, and seemingly others. When you updated the experimental v.0.8.9.1 and "fixed work tabs" after someone reported that prisoners "Forced to Work" would not appear. It worked previously, so i believe it has to do with something you changed...

Beta 0.8.9.1 unstable

**Comment by gruz123** [comment]
same...

**Comment by Aviuz** [comment]
bill button temporary disabled in 0.8.9.2

scheduled for re-enabling

**Comment by Aviuz** [comment]
fixed in 0.8.9.4
