### ISSUE TITLE
Excluding sleeping/recovering prisoners from being supervised not working

### ISSUE THREAD

**Issue by alexander-q** [Aviuz/PrisonLabor#79]
I had two prisoners. One was inside a prison-designated area, with the main door unlocked via the "locks" mod. He was in bed recovering from wounds. The second prisoner was out in the field mining. The sentry was standing by the first prisoners bed, watching him. This allowed the other prisoners motivation to drop while unwatched, and he escaped. 

What logic is used to determine which prisoner the sentry will watch?

**Comment by Aviuz** [comment]
It seems that my patches fixing old bugs are not working anymore.

They are very code sensitive, as all my harmony patches. So every little change to specific part of the game can result in fail on entire patch.

Thank you for reporting, this will be for sure restored to previous state.

**Comment by Aviuz** [comment]
it should work in 0.9.3
