### ISSUE TITLE
Only Prisoners do the Work

### ISSUE THREAD

**Issue by peter233** [Aviuz/PrisonLabor#85]
my colonist do work but if i get a prisoner they stop to work. Only the prisoner work. and if the Prisoners die there is nobody who can work. i have a savegame.

[onlyPrisonersWork.zip](https://github.com/Aviuz/PrisonLabor/files/1585904/onlyPrisonersWork.zip)

**Comment by Aviuz** [comment]
Thank you for bug report, but I have few questions:

1. Does colonists work before capturing **first** prisoner?
2. Does it reset after reloading save (with no prisoners, and with prisoners)?
3. Do you have set that prisoners do all types of job? If no, does colonists can work with work that isn't included to labor types?

**Comment by peter233** [comment]
1. yes
2. no
3. yes

its the button that defines the prison area. colonist dont do work if its in the prison area. and + they dont haul there(if i want give my prisoners clothing with a 1x1 stockpile, the colonist ignore the stockpile.).

one bug more. the prisoners cant sow healroot. nobody can not even the 8+ skilled prisoners in growing.

**Comment by EricChen1248** [comment]
Can confirm that this is an issue. I think it either needs to be more clearer that "Prison Labor Area" means that only prisoners will work, or allow colonists to work there as well.

**Comment by Aviuz** [comment]
@EricChen1248 
Thank you for you feedback, but for future I need to ask you to be consistent about a topic.

Bug does not appear at normal conditions (vanilla game with only PrisonLabor + Locks installed).
To actually fix this issue I need to **reproduce** the bug. If you can please provide info about:
 - is this happening to all your saves?
 - what is your mod list, and which mod you assume is not compatible
