### ISSUE TITLE
Prisoners never wear clothing

### ISSUE THREAD

**Issue by JonnyNova** [Aviuz/PrisonLabor#89]
Prisoners who have access to clothing will never wear it even if naked. Seems to be related to how their jobs are handled

**Comment by Aviuz** [comment]
https://github.com/Aviuz/PrisonExpansion

Prisoner do not pick up clothes that are outside their cells.

Prisoners do not pick up clothes when working.

This missing feature will be implemented in mod linked above.

**Comment by JonnyNova** [comment]
Is it intentional that they never pick up anything out of a stockpile to wear? My issue was that the clothing was in stockpiles in their room

**Comment by Aviuz** [comment]
> the clothing was in stockpiles in their room
If so you need to cut off labor by closing cell door or disabling labor.
They will only pick up t-shirts and pants.
It's vanilla mechanics.
Try lockers linked above.
